select * from supply_chain_data;

-- renaming the columns --

ALTER TABLE supply_chain_data 
CHANGE COLUMN `Product type` product_type TEXT,
CHANGE COLUMN `SKU` sku TEXT,
CHANGE COLUMN `Price` price DOUBLE,
CHANGE COLUMN `Availability` availability INT,
CHANGE COLUMN `Number of products sold` number_of_products_sold INT,
CHANGE COLUMN `Revenue generated` revenue_generated DOUBLE,
CHANGE COLUMN `Customer demographics` customer_demographics TEXT,
CHANGE COLUMN `Stock levels` stock_levels INT,
CHANGE COLUMN `Lead times` lead_times INT,
CHANGE COLUMN `Order quantities` order_quantities INT,
CHANGE COLUMN `Shipping times` shipping_times INT,
CHANGE COLUMN `Shipping carriers` shipping_carriers TEXT,
CHANGE COLUMN `Shipping costs` shipping_costs DOUBLE,
CHANGE COLUMN `Supplier name` supplier_name TEXT,
CHANGE COLUMN `Location` location TEXT,
CHANGE COLUMN `Lead time` lead_time INT,
CHANGE COLUMN `Production volumes` production_volumes INT,
CHANGE COLUMN `Manufacturing lead time` manufacturing_lead_time INT,
CHANGE COLUMN `Manufacturing costs` manufacturing_costs DOUBLE,
CHANGE COLUMN `Inspection results` inspection_results TEXT,
CHANGE COLUMN `Defect rates` defect_rates DOUBLE,
CHANGE COLUMN `Transportation modes` transportation_modes TEXT,
CHANGE COLUMN `Routes` routes TEXT,
CHANGE COLUMN `Costs` costs DOUBLE;


-- checking missing values -- none --

SELECT 
    COUNT(*) AS total_rows,
    COUNT(product_type) AS product_type_count,
    COUNT(SKU) AS SKU_count,
    COUNT(price) AS price_count,
    COUNT(availability) AS availability_count
FROM supply_chain_data;

-- Checking Duplicates -- none --

SELECT count(distinct SKU)
FROM supply_chain_data; 

-- Sales and Revenue Analysis --

select sum(number_of_products_sold) as sales, sum(revenue_generated) as total_revenue, sum(costs + manufacturing_costs + shipping_costs) as total_cost, sum(revenue_generated)-sum(costs + manufacturing_costs + shipping_costs) as total_profit 
from supply_chain_data;

-- Product sold and their revenue --

select product_type, sum(number_of_products_sold) as sales, sum(revenue_generated) as total_revenue
from supply_chain_data
group by product_type
order by total_revenue desc;

select product_type, AVG(price) as avg_price 
from supply_chain_data
group by product_type;

select 
 product_type,
 sum(revenue_generated) as total_revenue,
 sum(costs + shipping_costs + manufacturing_costs) as total_cost,
 (sum(revenue_generated) - sum(costs + shipping_costs + manufacturing_costs)) as total_profit,
 (sum(revenue_generated) - sum(costs + shipping_costs + manufacturing_costs))/sum(revenue_generated)*100 as profit_margin
from supply_chain_data
group by product_type
order by total_profit desc;

-- top product and revenue generated by gender --

select customer_demographics, count(customer_demographics) as total_count
from supply_chain_data
group by customer_demographics;

-- revenue --

select customer_demographics, sum(revenue_generated) as total_revenue
from supply_chain_data
group by customer_demographics
order by total_revenue desc;

-- top product by gender --

select customer_demographics, product_type , sum(number_of_products_sold) as total_sales 
from supply_chain_data
group by product_type, customer_demographics
order by customer_demographics, total_sales desc;

SELECT customer_demographics, product_type, 
       SUM(stock_levels) AS total_stock, 
       SUM(number_of_products_sold) AS total_sold
FROM supply_chain_data
GROUP BY customer_demographics, product_type
ORDER BY customer_demographics, total_sold DESC;

-- Location wise revenue --

select location, sum(revenue_generated) as total_revenue
from supply_chain_data
group by location
order by total_revenue desc;

select location, product_type, sum(revenue_generated) as total_revenue
from supply_chain_data
group by location, product_type
order by location, total_revenue desc;

-- Inventory & Stock Analysis --

-- Stock levels by product_type -- 

select product_type, sum(stock_levels) as total_stock 
from supply_chain_data
group by product_type;

-- Stock availabilty rate -- 

SELECT 
    (SUM(stock_levels) / SUM(availability)) * 100 AS stock_availability_rate
FROM supply_chain_data;

-- Out of stock or low stock products --

select SKU, product_type, stock_levels
from supply_chain_data
where stock_levels < 10
order by stock_levels desc;

-- Stock vs sales performance --
select product_type, sum(stock_levels) as total_stocks , sum(number_of_products_sold) as total_sales
 from supply_chain_data
 group by product_type;
 
-- stock turnover rate --

select product_type, 
(sum(number_of_products_sold)/avg(stock_levels)) as stock_turnover_rate
from supply_chain_data
group by product_type;

-- Supply chain Efficiency and logistics Analysis --

 -- Lead Time vs shipping cost --
 
 select supplier_name, avg(lead_time) as avg_lead_time, avg(shipping_costs) as avg_ship_cost  
 from supply_chain_data
 group by supplier_name
 order by avg_lead_time asc;
  
 
 -- Most used transportation modes --
 
 select transportation_modes, count(transportation_modes) as count
 from supply_chain_data
 group by transportation_modes
 order by count desc;
 
 select transportation_modes,
 avg(shipping_times),
 avg(shipping_costs) 
 from supply_chain_data
 group by transportation_modes;
 
 -- Shipping cost for carriers --
 
 select shipping_carriers, avg(shipping_costs) as avg_ship_cost
 from supply_chain_data
 group by shipping_carriers
 order by avg_ship_cost desc;
 
 -- order quantities vs stock level --

select product_type, avg(stock_levels) as avg_stock_levels, avg(order_quantities) as avg_order_quant
from supply_chain_data
group by product_type;

 -- route optimization --
 
 select routes , avg(shipping_times) as avg_ship_time, avg(shipping_costs) as avg_ship_cost
 from supply_chain_data
 group by routes;
 
 -- Quality and Defect Analysis --
 
 -- defect rate by product type --
 
 select product_type, avg(defect_rates) as avg_defect_rates
 from supply_chain_data
 group by product_type;
 
 -- defect rate by supplier --
 
select supplier_name, avg(defect_rates) as avg_defect_rates
from supply_chain_data
group by supplier_name;

-- inspection results --

select inspection_results, count(inspection_results) as count
from supply_chain_data
group by inspection_results;

-- inspection results and defect --

select inspection_results,
avg(defect_rates) as avg_defect_rates
from supply_chain_data
group by inspection_results;

-- location --

select location, avg(defect_rates) as avg_defect_rates
from supply_chain_data
group by location
order by avg_defect_rates desc;

select location, production_volumes, avg(defect_rates) as avg_defect_rates
from supply_chain_data
group by location, production_volumes
order by avg_defect_rates desc;

-- Cost and Profitabily Analysis --

-- cost breakdown --

select sum(manufacturing_costs) as manufacturing_costs, sum(shipping_costs) as shipping_costs, sum(costs) as total_cost
from supply_chain_data;

-- total cost --

select sum(manufacturing_costs + shipping_costs + costs) as total_cost
from supply_chain_data;

-- for each product --

select product_type, sum(manufacturing_costs) as manufacturing_costs from supply_chain_data
group by product_type;

select 
 product_type,
 sum(revenue_generated) as total_revenue,
 sum(costs + shipping_costs + manufacturing_costs) as total_cost,
 (sum(revenue_generated) - sum(costs + shipping_costs + manufacturing_costs)) as total_profit,
 (sum(revenue_generated) - sum(costs + shipping_costs + manufacturing_costs))/sum(revenue_generated)*100 as profit_margin
from supply_chain_data
group by product_type
order by total_profit desc;

-- supplier profit and costs --

select 
 supplier_name,
 sum(revenue_generated) as revenue,
 sum(costs + shipping_costs + manufacturing_costs) as total_cost,
 (sum(revenue_generated) - sum(costs + shipping_costs + manufacturing_costs)) as total_profit
from supply_chain_data
group by supplier_name
order by total_profit desc;


